<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Structa.Core\Structa.Core.csproj" />
    <ProjectReference Include="..\Structa.Geometry\Structa.Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGL" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
